eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application.name: blueorgreengateway
  config:
    import: "optional:configserver:http://localhost:8888"
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
server:
  port: 8383

management:
  endpoints:
    web:
      exposure:
        include: "*"
