spring.application.name: blueorgreengateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
server:
  port: 8383

management:
  endpoints:
    web:
      exposure:
        include: "*"
