spring.application.name: blueorgreengateway
spring.config.import: "optional:configserver:http://localhost:8888"
server.port: 8383

logging.level.org.springframework.cloud.gateway: DEBUG
wavefront.application.name: color-app
